set JAVA_HOME=%YAALI_JAVA%
echo JAVA_HOME=%JAVA_HOME%

set MVN_HOME=%YAALI_MVN%
echo MVN_HOME=%MVN_HOME%

set HOSTNAME=%COMPUTERNAME%
echo HOSTNAME=%HOSTNAME%

set PATH=%JAVA_HOME%\bin\;%MVN_HOME%\bin;%PATH%
echo PATH= %PATH%

