DROP TABLE IF EXISTS TRADE;

CREATE TABLE TRADE (

	ID BIGINT NOT NULL,
	TRADE_ID NUMERIC(10, 0) NOT NULL,
	TRADE_VERSION NUMERIC(3, 0) NOT NULL,
	COUNTERPARTY_ID VARCHAR(100),
	BOOK_ID VARCHAR(100),
	MATURITY_DATE TIMESTAMP NOT NULL,
	CREATED_DATE TIMESTAMP NOT NULL,
	EXPIRED BOOLEAN NOT NULL,
	VERSION NUMERIC(10, 0) DEFAULT 1,
	PRIMARY KEY(ID)
);


DROP SEQUENCE IF EXISTS SEQ_TRADE_STORE;

CREATE SEQUENCE SEQ_TRADE_STORE 
	START WITH 1
	INCREMENT BY 1
	NOMINVALUE NOMAXVALUE NOCACHE;  
	
INSERT INTO TRADE (ID, TRADE_ID, TRADE_VERSION,  COUNTERPARTY_ID, BOOK_ID, MATURITY_DATE, CREATED_DATE, EXPIRED) VALUES (SEQ_TRADE_STORE.NEXTVAL, 1, 1, 'CP-1', 'B1', current_date +10 + time '23:00', sysdate(), 0);	
INSERT INTO TRADE (ID, TRADE_ID, TRADE_VERSION,  COUNTERPARTY_ID, BOOK_ID, MATURITY_DATE, CREATED_DATE, EXPIRED) VALUES (SEQ_TRADE_STORE.NEXTVAL, 1, 2, 'CP-2', 'B2', current_date -1, sysdate(), 0);	
INSERT INTO TRADE (ID, TRADE_ID, TRADE_VERSION,  COUNTERPARTY_ID, BOOK_ID, MATURITY_DATE, CREATED_DATE, EXPIRED) VALUES (SEQ_TRADE_STORE.NEXTVAL, 1, 3, 'CP-3', 'B3', current_date +12 + time '23:00', sysdate(), 0);	
INSERT INTO TRADE (ID, TRADE_ID, TRADE_VERSION,  COUNTERPARTY_ID, BOOK_ID, MATURITY_DATE, CREATED_DATE, EXPIRED) VALUES (SEQ_TRADE_STORE.NEXTVAL, 2, 1, 'CP-1', 'B1', sysdate(), sysdate(), 0);	

COMMIT;
	